# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fitapp
    networks:
      - fitapp
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    networks:
      - fitapp
      
volumes:
  mysql_data:
    driver: local
    
networks:
  fitapp:
    driver: bridge